/* Generated By:JJTree: Do not edit this line. ASTImportDeclaration.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTImportDeclaration extends SimpleNode {
  public ASTImportDeclaration(int id) {
    super(id);
    isStatic = false;
  }

  public ASTImportDeclaration(SyntaxAnalysis p, int id) {
    super(p, id);
    isStatic = false;
  }

  public boolean isStatic() {
    return isStatic;
  }

  public void setStatic(boolean aStatic) {
    isStatic = aStatic;
  }

  private boolean isStatic;

}
/* JavaCC - OriginalChecksum=09e667c3c73be52d385e020d99707048 (do not edit this line) */
